input_type = "CSV"
files = []
directories = [ "../baseballdatabank/core" ]
create_db = true
gen_models = true
gen_webserver = true
gen_sql = true 

[output]
  output_dir = ".."
  project_name = "baseball_stats_api"

[output_db]
  db_type = "sqlite"
  db_uri = "../baseball_stats_api/database/baseball_stats.db"