input_type = "CSV"
files = [ "../baseballdatabank/core/Batting.csv" ]
directories = []
create_db = true
gen_models = true
gen_webserver = false
gen_sql = true 

[output]
  output_dir = ".."
  project_name = "baseball_stats_api"

[output_db]
  db_type = "sqlite"
  db_uri = "./bd_batting.db"