input_type = "CSV"
files = [ "../hockey-databank/Scoring.csv" ]
directories = [ "../hockey-databank" ]
create_db = true
gen_models = true
gen_webserver = true
gen_sql = true 

[output]
  output_dir = ".."
  project_name = "hockey_db_api"

[output_db]
  db_type = "sqlite"
  db_uri = "../hockey-db/database/hockey_databank_2017.db"