version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.31.0-node-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Install Rust
          command: rustup install stable
      - run:
          name: Stable Build
          command:  |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build
      - run:
          name: Test
          command: rustup run stable cargo test
      - run:
          name: Upload Coverage
          command: ls -a
          #command: ./scripts/codecov.sh
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "~./target"